using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DalWebSite
{
    /// <summary>
    /// Controller class for ps_doctors_des
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class PsDoctorsDeController
    {
        // Preload our schema..
        PsDoctorsDe thisSchemaLoad = new PsDoctorsDe();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public PsDoctorsDeCollection FetchAll()
        {
            PsDoctorsDeCollection coll = new PsDoctorsDeCollection();
            Query qry = new Query(PsDoctorsDe.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public PsDoctorsDeCollection FetchByID(object IdIndex)
        {
            PsDoctorsDeCollection coll = new PsDoctorsDeCollection().Where("id_index", IdIndex).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public PsDoctorsDeCollection FetchByQuery(Query qry)
        {
            PsDoctorsDeCollection coll = new PsDoctorsDeCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdIndex)
        {
            return (PsDoctorsDe.Delete(IdIndex) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdIndex)
        {
            return (PsDoctorsDe.Destroy(IdIndex) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? Id,int? OldId,string Description)
	    {
		    PsDoctorsDe item = new PsDoctorsDe();
		    
            item.Id = Id;
            
            item.OldId = OldId;
            
            item.Description = Description;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int IdIndex,int? Id,int? OldId,string Description)
	    {
		    PsDoctorsDe item = new PsDoctorsDe();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.IdIndex = IdIndex;
				
			item.Id = Id;
				
			item.OldId = OldId;
				
			item.Description = Description;
				
	        item.Save(UserName);
	    }
    }
}
