using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the PsDoctorsDe class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class PsDoctorsDeCollection : ActiveList<PsDoctorsDe, PsDoctorsDeCollection>
	{	   
		public PsDoctorsDeCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>PsDoctorsDeCollection</returns>
		public PsDoctorsDeCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                PsDoctorsDe o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the ps_doctors_des table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class PsDoctorsDe : ActiveRecord<PsDoctorsDe>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public PsDoctorsDe()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public PsDoctorsDe(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public PsDoctorsDe(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public PsDoctorsDe(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("ps_doctors_des", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"psDb_user";
				//columns
				
				TableSchema.TableColumn colvarIdIndex = new TableSchema.TableColumn(schema);
				colvarIdIndex.ColumnName = "id_index";
				colvarIdIndex.DataType = DbType.Int32;
				colvarIdIndex.MaxLength = 0;
				colvarIdIndex.AutoIncrement = true;
				colvarIdIndex.IsNullable = false;
				colvarIdIndex.IsPrimaryKey = true;
				colvarIdIndex.IsForeignKey = false;
				colvarIdIndex.IsReadOnly = false;
				colvarIdIndex.DefaultSetting = @"";
				colvarIdIndex.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIdIndex);
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = false;
				colvarId.IsNullable = true;
				colvarId.IsPrimaryKey = false;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarOldId = new TableSchema.TableColumn(schema);
				colvarOldId.ColumnName = "old_id";
				colvarOldId.DataType = DbType.Int32;
				colvarOldId.MaxLength = 0;
				colvarOldId.AutoIncrement = false;
				colvarOldId.IsNullable = true;
				colvarOldId.IsPrimaryKey = false;
				colvarOldId.IsForeignKey = false;
				colvarOldId.IsReadOnly = false;
				colvarOldId.DefaultSetting = @"";
				colvarOldId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarOldId);
				
				TableSchema.TableColumn colvarDescription = new TableSchema.TableColumn(schema);
				colvarDescription.ColumnName = "description";
				colvarDescription.DataType = DbType.String;
				colvarDescription.MaxLength = 1073741823;
				colvarDescription.AutoIncrement = false;
				colvarDescription.IsNullable = true;
				colvarDescription.IsPrimaryKey = false;
				colvarDescription.IsForeignKey = false;
				colvarDescription.IsReadOnly = false;
				colvarDescription.DefaultSetting = @"";
				colvarDescription.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDescription);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("ps_doctors_des",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("IdIndex")]
		[Bindable(true)]
        [DataMember]
		public int IdIndex 
		{
			get { return GetColumnValue<int>(Columns.IdIndex); }
			set { SetColumnValue(Columns.IdIndex, value); }
		}
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int? Id 
		{
			get { return GetColumnValue<int?>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("OldId")]
		[Bindable(true)]
        [DataMember]
		public int? OldId 
		{
			get { return GetColumnValue<int?>(Columns.OldId); }
			set { SetColumnValue(Columns.OldId, value); }
		}
		  
		[XmlAttribute("Description")]
		[Bindable(true)]
        [DataMember]
		public string Description 
		{
			get { return GetColumnValue<string>(Columns.Description); }
			set { SetColumnValue(Columns.Description, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int? varId,int? varOldId,string varDescription)
		{
			PsDoctorsDe item = new PsDoctorsDe();
			
			item.Id = varId;
			
			item.OldId = varOldId;
			
			item.Description = varDescription;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varIdIndex,int? varId,int? varOldId,string varDescription)
		{
			PsDoctorsDe item = new PsDoctorsDe();
			
				item.IdIndex = varIdIndex;
			
				item.Id = varId;
			
				item.OldId = varOldId;
			
				item.Description = varDescription;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdIndexColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn OldIdColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn DescriptionColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string IdIndex = @"id_index";
			 public static string Id = @"id";
			 public static string OldId = @"old_id";
			 public static string Description = @"description";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
