using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DalWebSite
{
    /// <summary>
    /// Controller class for TblAppointmentConfig
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblAppointmentConfigController
    {
        // Preload our schema..
        TblAppointmentConfig thisSchemaLoad = new TblAppointmentConfig();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblAppointmentConfigCollection FetchAll()
        {
            TblAppointmentConfigCollection coll = new TblAppointmentConfigCollection();
            Query qry = new Query(TblAppointmentConfig.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblAppointmentConfigCollection FetchByID(object Id)
        {
            TblAppointmentConfigCollection coll = new TblAppointmentConfigCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblAppointmentConfigCollection FetchByQuery(Query qry)
        {
            TblAppointmentConfigCollection coll = new TblAppointmentConfigCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblAppointmentConfig.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblAppointmentConfig.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? AShift,string ADate,string AStartTime,int? ATime,int? ANum,int? ADoctorId,DateTime? ADateTime,byte? AActive)
	    {
		    TblAppointmentConfig item = new TblAppointmentConfig();
		    
            item.AShift = AShift;
            
            item.ADate = ADate;
            
            item.AStartTime = AStartTime;
            
            item.ATime = ATime;
            
            item.ANum = ANum;
            
            item.ADoctorId = ADoctorId;
            
            item.ADateTime = ADateTime;
            
            item.AActive = AActive;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int? AShift,string ADate,string AStartTime,int? ATime,int? ANum,int? ADoctorId,DateTime? ADateTime,byte? AActive)
	    {
		    TblAppointmentConfig item = new TblAppointmentConfig();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.AShift = AShift;
				
			item.ADate = ADate;
				
			item.AStartTime = AStartTime;
				
			item.ATime = ATime;
				
			item.ANum = ANum;
				
			item.ADoctorId = ADoctorId;
				
			item.ADateTime = ADateTime;
				
			item.AActive = AActive;
				
	        item.Save(UserName);
	    }
    }
}
