using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the TblAppointmentConfig class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class TblAppointmentConfigCollection : ActiveList<TblAppointmentConfig, TblAppointmentConfigCollection>
	{	   
		public TblAppointmentConfigCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblAppointmentConfigCollection</returns>
		public TblAppointmentConfigCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblAppointmentConfig o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblAppointmentConfig table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class TblAppointmentConfig : ActiveRecord<TblAppointmentConfig>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblAppointmentConfig()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblAppointmentConfig(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblAppointmentConfig(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblAppointmentConfig(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblAppointmentConfig", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarAShift = new TableSchema.TableColumn(schema);
				colvarAShift.ColumnName = "aShift";
				colvarAShift.DataType = DbType.Int32;
				colvarAShift.MaxLength = 0;
				colvarAShift.AutoIncrement = false;
				colvarAShift.IsNullable = true;
				colvarAShift.IsPrimaryKey = false;
				colvarAShift.IsForeignKey = false;
				colvarAShift.IsReadOnly = false;
				colvarAShift.DefaultSetting = @"";
				colvarAShift.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAShift);
				
				TableSchema.TableColumn colvarADate = new TableSchema.TableColumn(schema);
				colvarADate.ColumnName = "aDate";
				colvarADate.DataType = DbType.AnsiString;
				colvarADate.MaxLength = 0;
				colvarADate.AutoIncrement = false;
				colvarADate.IsNullable = true;
				colvarADate.IsPrimaryKey = false;
				colvarADate.IsForeignKey = false;
				colvarADate.IsReadOnly = false;
				colvarADate.DefaultSetting = @"";
				colvarADate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarADate);
				
				TableSchema.TableColumn colvarAStartTime = new TableSchema.TableColumn(schema);
				colvarAStartTime.ColumnName = "aStartTime";
				colvarAStartTime.DataType = DbType.AnsiString;
				colvarAStartTime.MaxLength = 0;
				colvarAStartTime.AutoIncrement = false;
				colvarAStartTime.IsNullable = true;
				colvarAStartTime.IsPrimaryKey = false;
				colvarAStartTime.IsForeignKey = false;
				colvarAStartTime.IsReadOnly = false;
				colvarAStartTime.DefaultSetting = @"";
				colvarAStartTime.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAStartTime);
				
				TableSchema.TableColumn colvarATime = new TableSchema.TableColumn(schema);
				colvarATime.ColumnName = "aTime";
				colvarATime.DataType = DbType.Int32;
				colvarATime.MaxLength = 0;
				colvarATime.AutoIncrement = false;
				colvarATime.IsNullable = true;
				colvarATime.IsPrimaryKey = false;
				colvarATime.IsForeignKey = false;
				colvarATime.IsReadOnly = false;
				colvarATime.DefaultSetting = @"";
				colvarATime.ForeignKeyTableName = "";
				schema.Columns.Add(colvarATime);
				
				TableSchema.TableColumn colvarANum = new TableSchema.TableColumn(schema);
				colvarANum.ColumnName = "aNum";
				colvarANum.DataType = DbType.Int32;
				colvarANum.MaxLength = 0;
				colvarANum.AutoIncrement = false;
				colvarANum.IsNullable = true;
				colvarANum.IsPrimaryKey = false;
				colvarANum.IsForeignKey = false;
				colvarANum.IsReadOnly = false;
				colvarANum.DefaultSetting = @"";
				colvarANum.ForeignKeyTableName = "";
				schema.Columns.Add(colvarANum);
				
				TableSchema.TableColumn colvarADoctorId = new TableSchema.TableColumn(schema);
				colvarADoctorId.ColumnName = "aDoctorId";
				colvarADoctorId.DataType = DbType.Int32;
				colvarADoctorId.MaxLength = 0;
				colvarADoctorId.AutoIncrement = false;
				colvarADoctorId.IsNullable = true;
				colvarADoctorId.IsPrimaryKey = false;
				colvarADoctorId.IsForeignKey = false;
				colvarADoctorId.IsReadOnly = false;
				colvarADoctorId.DefaultSetting = @"";
				colvarADoctorId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarADoctorId);
				
				TableSchema.TableColumn colvarADateTime = new TableSchema.TableColumn(schema);
				colvarADateTime.ColumnName = "aDateTime";
				colvarADateTime.DataType = DbType.DateTime;
				colvarADateTime.MaxLength = 0;
				colvarADateTime.AutoIncrement = false;
				colvarADateTime.IsNullable = true;
				colvarADateTime.IsPrimaryKey = false;
				colvarADateTime.IsForeignKey = false;
				colvarADateTime.IsReadOnly = false;
				colvarADateTime.DefaultSetting = @"";
				colvarADateTime.ForeignKeyTableName = "";
				schema.Columns.Add(colvarADateTime);
				
				TableSchema.TableColumn colvarAActive = new TableSchema.TableColumn(schema);
				colvarAActive.ColumnName = "aActive";
				colvarAActive.DataType = DbType.Byte;
				colvarAActive.MaxLength = 0;
				colvarAActive.AutoIncrement = false;
				colvarAActive.IsNullable = true;
				colvarAActive.IsPrimaryKey = false;
				colvarAActive.IsForeignKey = false;
				colvarAActive.IsReadOnly = false;
				colvarAActive.DefaultSetting = @"";
				colvarAActive.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAActive);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("TblAppointmentConfig",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("AShift")]
		[Bindable(true)]
        [DataMember]
		public int? AShift 
		{
			get { return GetColumnValue<int?>(Columns.AShift); }
			set { SetColumnValue(Columns.AShift, value); }
		}
		  
		[XmlAttribute("ADate")]
		[Bindable(true)]
        [DataMember]
		public string ADate 
		{
			get { return GetColumnValue<string>(Columns.ADate); }
			set { SetColumnValue(Columns.ADate, value); }
		}
		  
		[XmlAttribute("AStartTime")]
		[Bindable(true)]
        [DataMember]
		public string AStartTime 
		{
			get { return GetColumnValue<string>(Columns.AStartTime); }
			set { SetColumnValue(Columns.AStartTime, value); }
		}
		  
		[XmlAttribute("ATime")]
		[Bindable(true)]
        [DataMember]
		public int? ATime 
		{
			get { return GetColumnValue<int?>(Columns.ATime); }
			set { SetColumnValue(Columns.ATime, value); }
		}
		  
		[XmlAttribute("ANum")]
		[Bindable(true)]
        [DataMember]
		public int? ANum 
		{
			get { return GetColumnValue<int?>(Columns.ANum); }
			set { SetColumnValue(Columns.ANum, value); }
		}
		  
		[XmlAttribute("ADoctorId")]
		[Bindable(true)]
        [DataMember]
		public int? ADoctorId 
		{
			get { return GetColumnValue<int?>(Columns.ADoctorId); }
			set { SetColumnValue(Columns.ADoctorId, value); }
		}
		  
		[XmlAttribute("ADateTime")]
		[Bindable(true)]
        [DataMember]
		public DateTime? ADateTime 
		{
			get { return GetColumnValue<DateTime?>(Columns.ADateTime); }
			set { SetColumnValue(Columns.ADateTime, value); }
		}
		  
		[XmlAttribute("AActive")]
		[Bindable(true)]
        [DataMember]
		public byte? AActive 
		{
			get { return GetColumnValue<byte?>(Columns.AActive); }
			set { SetColumnValue(Columns.AActive, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int? varAShift,string varADate,string varAStartTime,int? varATime,int? varANum,int? varADoctorId,DateTime? varADateTime,byte? varAActive)
		{
			TblAppointmentConfig item = new TblAppointmentConfig();
			
			item.AShift = varAShift;
			
			item.ADate = varADate;
			
			item.AStartTime = varAStartTime;
			
			item.ATime = varATime;
			
			item.ANum = varANum;
			
			item.ADoctorId = varADoctorId;
			
			item.ADateTime = varADateTime;
			
			item.AActive = varAActive;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,int? varAShift,string varADate,string varAStartTime,int? varATime,int? varANum,int? varADoctorId,DateTime? varADateTime,byte? varAActive)
		{
			TblAppointmentConfig item = new TblAppointmentConfig();
			
				item.Id = varId;
			
				item.AShift = varAShift;
			
				item.ADate = varADate;
			
				item.AStartTime = varAStartTime;
			
				item.ATime = varATime;
			
				item.ANum = varANum;
			
				item.ADoctorId = varADoctorId;
			
				item.ADateTime = varADateTime;
			
				item.AActive = varAActive;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn AShiftColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn ADateColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn AStartTimeColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn ATimeColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn ANumColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn ADoctorIdColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn ADateTimeColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn AActiveColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string AShift = @"aShift";
			 public static string ADate = @"aDate";
			 public static string AStartTime = @"aStartTime";
			 public static string ATime = @"aTime";
			 public static string ANum = @"aNum";
			 public static string ADoctorId = @"aDoctorId";
			 public static string ADateTime = @"aDateTime";
			 public static string AActive = @"aActive";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
