using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DalWebSite
{
    /// <summary>
    /// Controller class for TblComment
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblCommentController
    {
        // Preload our schema..
        TblComment thisSchemaLoad = new TblComment();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblCommentCollection FetchAll()
        {
            TblCommentCollection coll = new TblCommentCollection();
            Query qry = new Query(TblComment.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblCommentCollection FetchByID(object Id)
        {
            TblCommentCollection coll = new TblCommentCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblCommentCollection FetchByQuery(Query qry)
        {
            TblCommentCollection coll = new TblCommentCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblComment.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblComment.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string CName,int CDoctorId,string CDes,DateTime? CSaveDate,bool? CStatus,byte? CSuggest)
	    {
		    TblComment item = new TblComment();
		    
            item.CName = CName;
            
            item.CDoctorId = CDoctorId;
            
            item.CDes = CDes;
            
            item.CSaveDate = CSaveDate;
            
            item.CStatus = CStatus;
            
            item.CSuggest = CSuggest;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string CName,int CDoctorId,string CDes,DateTime? CSaveDate,bool? CStatus,byte? CSuggest)
	    {
		    TblComment item = new TblComment();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.CName = CName;
				
			item.CDoctorId = CDoctorId;
				
			item.CDes = CDes;
				
			item.CSaveDate = CSaveDate;
				
			item.CStatus = CStatus;
				
			item.CSuggest = CSuggest;
				
	        item.Save(UserName);
	    }
    }
}
