using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the TblComment class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class TblCommentCollection : ActiveList<TblComment, TblCommentCollection>
	{	   
		public TblCommentCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblCommentCollection</returns>
		public TblCommentCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblComment o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblComment table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class TblComment : ActiveRecord<TblComment>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblComment()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblComment(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblComment(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblComment(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblComment", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarCName = new TableSchema.TableColumn(schema);
				colvarCName.ColumnName = "cName";
				colvarCName.DataType = DbType.String;
				colvarCName.MaxLength = 50;
				colvarCName.AutoIncrement = false;
				colvarCName.IsNullable = true;
				colvarCName.IsPrimaryKey = false;
				colvarCName.IsForeignKey = false;
				colvarCName.IsReadOnly = false;
				colvarCName.DefaultSetting = @"";
				colvarCName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCName);
				
				TableSchema.TableColumn colvarCDoctorId = new TableSchema.TableColumn(schema);
				colvarCDoctorId.ColumnName = "cDoctorId";
				colvarCDoctorId.DataType = DbType.Int32;
				colvarCDoctorId.MaxLength = 0;
				colvarCDoctorId.AutoIncrement = false;
				colvarCDoctorId.IsNullable = false;
				colvarCDoctorId.IsPrimaryKey = false;
				colvarCDoctorId.IsForeignKey = false;
				colvarCDoctorId.IsReadOnly = false;
				colvarCDoctorId.DefaultSetting = @"";
				colvarCDoctorId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCDoctorId);
				
				TableSchema.TableColumn colvarCDes = new TableSchema.TableColumn(schema);
				colvarCDes.ColumnName = "cDes";
				colvarCDes.DataType = DbType.String;
				colvarCDes.MaxLength = -1;
				colvarCDes.AutoIncrement = false;
				colvarCDes.IsNullable = true;
				colvarCDes.IsPrimaryKey = false;
				colvarCDes.IsForeignKey = false;
				colvarCDes.IsReadOnly = false;
				colvarCDes.DefaultSetting = @"";
				colvarCDes.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCDes);
				
				TableSchema.TableColumn colvarCSaveDate = new TableSchema.TableColumn(schema);
				colvarCSaveDate.ColumnName = "cSaveDate";
				colvarCSaveDate.DataType = DbType.DateTime;
				colvarCSaveDate.MaxLength = 0;
				colvarCSaveDate.AutoIncrement = false;
				colvarCSaveDate.IsNullable = true;
				colvarCSaveDate.IsPrimaryKey = false;
				colvarCSaveDate.IsForeignKey = false;
				colvarCSaveDate.IsReadOnly = false;
				colvarCSaveDate.DefaultSetting = @"";
				colvarCSaveDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCSaveDate);
				
				TableSchema.TableColumn colvarCStatus = new TableSchema.TableColumn(schema);
				colvarCStatus.ColumnName = "cStatus";
				colvarCStatus.DataType = DbType.Boolean;
				colvarCStatus.MaxLength = 0;
				colvarCStatus.AutoIncrement = false;
				colvarCStatus.IsNullable = true;
				colvarCStatus.IsPrimaryKey = false;
				colvarCStatus.IsForeignKey = false;
				colvarCStatus.IsReadOnly = false;
				colvarCStatus.DefaultSetting = @"";
				colvarCStatus.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCStatus);
				
				TableSchema.TableColumn colvarCSuggest = new TableSchema.TableColumn(schema);
				colvarCSuggest.ColumnName = "cSuggest";
				colvarCSuggest.DataType = DbType.Byte;
				colvarCSuggest.MaxLength = 0;
				colvarCSuggest.AutoIncrement = false;
				colvarCSuggest.IsNullable = true;
				colvarCSuggest.IsPrimaryKey = false;
				colvarCSuggest.IsForeignKey = false;
				colvarCSuggest.IsReadOnly = false;
				colvarCSuggest.DefaultSetting = @"";
				colvarCSuggest.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCSuggest);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("TblComment",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("CName")]
		[Bindable(true)]
        [DataMember]
		public string CName 
		{
			get { return GetColumnValue<string>(Columns.CName); }
			set { SetColumnValue(Columns.CName, value); }
		}
		  
		[XmlAttribute("CDoctorId")]
		[Bindable(true)]
        [DataMember]
		public int CDoctorId 
		{
			get { return GetColumnValue<int>(Columns.CDoctorId); }
			set { SetColumnValue(Columns.CDoctorId, value); }
		}
		  
		[XmlAttribute("CDes")]
		[Bindable(true)]
        [DataMember]
		public string CDes 
		{
			get { return GetColumnValue<string>(Columns.CDes); }
			set { SetColumnValue(Columns.CDes, value); }
		}
		  
		[XmlAttribute("CSaveDate")]
		[Bindable(true)]
        [DataMember]
		public DateTime? CSaveDate 
		{
			get { return GetColumnValue<DateTime?>(Columns.CSaveDate); }
			set { SetColumnValue(Columns.CSaveDate, value); }
		}
		  
		[XmlAttribute("CStatus")]
		[Bindable(true)]
        [DataMember]
		public bool? CStatus 
		{
			get { return GetColumnValue<bool?>(Columns.CStatus); }
			set { SetColumnValue(Columns.CStatus, value); }
		}
		  
		[XmlAttribute("CSuggest")]
		[Bindable(true)]
        [DataMember]
		public byte? CSuggest 
		{
			get { return GetColumnValue<byte?>(Columns.CSuggest); }
			set { SetColumnValue(Columns.CSuggest, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varCName,int varCDoctorId,string varCDes,DateTime? varCSaveDate,bool? varCStatus,byte? varCSuggest)
		{
			TblComment item = new TblComment();
			
			item.CName = varCName;
			
			item.CDoctorId = varCDoctorId;
			
			item.CDes = varCDes;
			
			item.CSaveDate = varCSaveDate;
			
			item.CStatus = varCStatus;
			
			item.CSuggest = varCSuggest;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varCName,int varCDoctorId,string varCDes,DateTime? varCSaveDate,bool? varCStatus,byte? varCSuggest)
		{
			TblComment item = new TblComment();
			
				item.Id = varId;
			
				item.CName = varCName;
			
				item.CDoctorId = varCDoctorId;
			
				item.CDes = varCDes;
			
				item.CSaveDate = varCSaveDate;
			
				item.CStatus = varCStatus;
			
				item.CSuggest = varCSuggest;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn CNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn CDoctorIdColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn CDesColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn CSaveDateColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn CStatusColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn CSuggestColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string CName = @"cName";
			 public static string CDoctorId = @"cDoctorId";
			 public static string CDes = @"cDes";
			 public static string CSaveDate = @"cSaveDate";
			 public static string CStatus = @"cStatus";
			 public static string CSuggest = @"cSuggest";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
