using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the TblComment class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class TblCommentCollection : ActiveList<TblComment, TblCommentCollection>
	{	   
		public TblCommentCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblCommentCollection</returns>
		public TblCommentCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblComment o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblComment table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class TblComment : ActiveRecord<TblComment>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblComment()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblComment(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblComment(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblComment(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblComment", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"psDb_user";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarName = new TableSchema.TableColumn(schema);
				colvarName.ColumnName = "name";
				colvarName.DataType = DbType.String;
				colvarName.MaxLength = 50;
				colvarName.AutoIncrement = false;
				colvarName.IsNullable = true;
				colvarName.IsPrimaryKey = false;
				colvarName.IsForeignKey = false;
				colvarName.IsReadOnly = false;
				colvarName.DefaultSetting = @"";
				colvarName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarName);
				
				TableSchema.TableColumn colvarSaveDate = new TableSchema.TableColumn(schema);
				colvarSaveDate.ColumnName = "saveDate";
				colvarSaveDate.DataType = DbType.DateTime;
				colvarSaveDate.MaxLength = 0;
				colvarSaveDate.AutoIncrement = false;
				colvarSaveDate.IsNullable = true;
				colvarSaveDate.IsPrimaryKey = false;
				colvarSaveDate.IsForeignKey = false;
				colvarSaveDate.IsReadOnly = false;
				colvarSaveDate.DefaultSetting = @"";
				colvarSaveDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSaveDate);
				
				TableSchema.TableColumn colvarDoctorId = new TableSchema.TableColumn(schema);
				colvarDoctorId.ColumnName = "doctorId";
				colvarDoctorId.DataType = DbType.Int32;
				colvarDoctorId.MaxLength = 0;
				colvarDoctorId.AutoIncrement = false;
				colvarDoctorId.IsNullable = true;
				colvarDoctorId.IsPrimaryKey = false;
				colvarDoctorId.IsForeignKey = false;
				colvarDoctorId.IsReadOnly = false;
				colvarDoctorId.DefaultSetting = @"";
				colvarDoctorId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDoctorId);
				
				TableSchema.TableColumn colvarDisplayStatus = new TableSchema.TableColumn(schema);
				colvarDisplayStatus.ColumnName = "displayStatus";
				colvarDisplayStatus.DataType = DbType.Byte;
				colvarDisplayStatus.MaxLength = 0;
				colvarDisplayStatus.AutoIncrement = false;
				colvarDisplayStatus.IsNullable = true;
				colvarDisplayStatus.IsPrimaryKey = false;
				colvarDisplayStatus.IsForeignKey = false;
				colvarDisplayStatus.IsReadOnly = false;
				
						colvarDisplayStatus.DefaultSetting = @"((0))";
				colvarDisplayStatus.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDisplayStatus);
				
				TableSchema.TableColumn colvarStatus = new TableSchema.TableColumn(schema);
				colvarStatus.ColumnName = "status";
				colvarStatus.DataType = DbType.Byte;
				colvarStatus.MaxLength = 0;
				colvarStatus.AutoIncrement = false;
				colvarStatus.IsNullable = true;
				colvarStatus.IsPrimaryKey = false;
				colvarStatus.IsForeignKey = false;
				colvarStatus.IsReadOnly = false;
				
						colvarStatus.DefaultSetting = @"((0))";
				colvarStatus.ForeignKeyTableName = "";
				schema.Columns.Add(colvarStatus);
				
				TableSchema.TableColumn colvarComment = new TableSchema.TableColumn(schema);
				colvarComment.ColumnName = "comment";
				colvarComment.DataType = DbType.AnsiString;
				colvarComment.MaxLength = -1;
				colvarComment.AutoIncrement = false;
				colvarComment.IsNullable = true;
				colvarComment.IsPrimaryKey = false;
				colvarComment.IsForeignKey = false;
				colvarComment.IsReadOnly = false;
				colvarComment.DefaultSetting = @"";
				colvarComment.ForeignKeyTableName = "";
				schema.Columns.Add(colvarComment);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("TblComment",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("Name")]
		[Bindable(true)]
        [DataMember]
		public string Name 
		{
			get { return GetColumnValue<string>(Columns.Name); }
			set { SetColumnValue(Columns.Name, value); }
		}
		  
		[XmlAttribute("SaveDate")]
		[Bindable(true)]
        [DataMember]
		public DateTime? SaveDate 
		{
			get { return GetColumnValue<DateTime?>(Columns.SaveDate); }
			set { SetColumnValue(Columns.SaveDate, value); }
		}
		  
		[XmlAttribute("DoctorId")]
		[Bindable(true)]
        [DataMember]
		public int? DoctorId 
		{
			get { return GetColumnValue<int?>(Columns.DoctorId); }
			set { SetColumnValue(Columns.DoctorId, value); }
		}
		  
		[XmlAttribute("DisplayStatus")]
		[Bindable(true)]
        [DataMember]
		public byte? DisplayStatus 
		{
			get { return GetColumnValue<byte?>(Columns.DisplayStatus); }
			set { SetColumnValue(Columns.DisplayStatus, value); }
		}
		  
		[XmlAttribute("Status")]
		[Bindable(true)]
        [DataMember]
		public byte? Status 
		{
			get { return GetColumnValue<byte?>(Columns.Status); }
			set { SetColumnValue(Columns.Status, value); }
		}
		  
		[XmlAttribute("Comment")]
		[Bindable(true)]
        [DataMember]
		public string Comment 
		{
			get { return GetColumnValue<string>(Columns.Comment); }
			set { SetColumnValue(Columns.Comment, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varName,DateTime? varSaveDate,int? varDoctorId,byte? varDisplayStatus,byte? varStatus,string varComment)
		{
			TblComment item = new TblComment();
			
			item.Name = varName;
			
			item.SaveDate = varSaveDate;
			
			item.DoctorId = varDoctorId;
			
			item.DisplayStatus = varDisplayStatus;
			
			item.Status = varStatus;
			
			item.Comment = varComment;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varName,DateTime? varSaveDate,int? varDoctorId,byte? varDisplayStatus,byte? varStatus,string varComment)
		{
			TblComment item = new TblComment();
			
				item.Id = varId;
			
				item.Name = varName;
			
				item.SaveDate = varSaveDate;
			
				item.DoctorId = varDoctorId;
			
				item.DisplayStatus = varDisplayStatus;
			
				item.Status = varStatus;
			
				item.Comment = varComment;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn NameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn SaveDateColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn DoctorIdColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn DisplayStatusColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn StatusColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn CommentColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string Name = @"name";
			 public static string SaveDate = @"saveDate";
			 public static string DoctorId = @"doctorId";
			 public static string DisplayStatus = @"displayStatus";
			 public static string Status = @"status";
			 public static string Comment = @"comment";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
