using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DalWebSite
{
    /// <summary>
    /// Controller class for TblSmallBanner
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblSmallBannerController
    {
        // Preload our schema..
        TblSmallBanner thisSchemaLoad = new TblSmallBanner();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblSmallBannerCollection FetchAll()
        {
            TblSmallBannerCollection coll = new TblSmallBannerCollection();
            Query qry = new Query(TblSmallBanner.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblSmallBannerCollection FetchByID(object Id)
        {
            TblSmallBannerCollection coll = new TblSmallBannerCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblSmallBannerCollection FetchByQuery(Query qry)
        {
            TblSmallBannerCollection coll = new TblSmallBannerCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblSmallBanner.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblSmallBanner.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Subject,string Subtitle,string Link,string TextColor,string Image,byte? Active)
	    {
		    TblSmallBanner item = new TblSmallBanner();
		    
            item.Subject = Subject;
            
            item.Subtitle = Subtitle;
            
            item.Link = Link;
            
            item.TextColor = TextColor;
            
            item.Image = Image;
            
            item.Active = Active;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string Subject,string Subtitle,string Link,string TextColor,string Image,byte? Active)
	    {
		    TblSmallBanner item = new TblSmallBanner();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Subject = Subject;
				
			item.Subtitle = Subtitle;
				
			item.Link = Link;
				
			item.TextColor = TextColor;
				
			item.Image = Image;
				
			item.Active = Active;
				
	        item.Save(UserName);
	    }
    }
}
