using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
// <This SubSonic version has been modified to now support Microsoft SQL Server 2008 TVP data structures. />
// <See http://stackoverflow.com/questions/2999570/subsonic-2-x-now-supports-tvps-sqldbtype-structure-datatables-for-sql-server . />
// <This version also supports WCF REST services. />
namespace DalWebSite
{
	/// <summary>
	/// Strongly-typed collection for the TblSmallBanner class.
	/// </summary>
    [Serializable]
    [CollectionDataContract]
	public partial class TblSmallBannerCollection : ActiveList<TblSmallBanner, TblSmallBannerCollection>
	{	   
		public TblSmallBannerCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblSmallBannerCollection</returns>
		public TblSmallBannerCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblSmallBanner o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblSmallBanner table.
	/// </summary>
	[Serializable]
    [DataContract]
	public partial class TblSmallBanner : ActiveRecord<TblSmallBanner>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblSmallBanner()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblSmallBanner(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblSmallBanner(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblSmallBanner(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblSmallBanner", TableType.Table, DataService.GetInstance("DbWebSiteConnectionString"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarSubject = new TableSchema.TableColumn(schema);
				colvarSubject.ColumnName = "subject";
				colvarSubject.DataType = DbType.String;
				colvarSubject.MaxLength = 50;
				colvarSubject.AutoIncrement = false;
				colvarSubject.IsNullable = true;
				colvarSubject.IsPrimaryKey = false;
				colvarSubject.IsForeignKey = false;
				colvarSubject.IsReadOnly = false;
				colvarSubject.DefaultSetting = @"";
				colvarSubject.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSubject);
				
				TableSchema.TableColumn colvarSubtitle = new TableSchema.TableColumn(schema);
				colvarSubtitle.ColumnName = "subtitle";
				colvarSubtitle.DataType = DbType.String;
				colvarSubtitle.MaxLength = 50;
				colvarSubtitle.AutoIncrement = false;
				colvarSubtitle.IsNullable = true;
				colvarSubtitle.IsPrimaryKey = false;
				colvarSubtitle.IsForeignKey = false;
				colvarSubtitle.IsReadOnly = false;
				colvarSubtitle.DefaultSetting = @"";
				colvarSubtitle.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSubtitle);
				
				TableSchema.TableColumn colvarLink = new TableSchema.TableColumn(schema);
				colvarLink.ColumnName = "link";
				colvarLink.DataType = DbType.String;
				colvarLink.MaxLength = 1000;
				colvarLink.AutoIncrement = false;
				colvarLink.IsNullable = true;
				colvarLink.IsPrimaryKey = false;
				colvarLink.IsForeignKey = false;
				colvarLink.IsReadOnly = false;
				colvarLink.DefaultSetting = @"";
				colvarLink.ForeignKeyTableName = "";
				schema.Columns.Add(colvarLink);
				
				TableSchema.TableColumn colvarTextColor = new TableSchema.TableColumn(schema);
				colvarTextColor.ColumnName = "textColor";
				colvarTextColor.DataType = DbType.String;
				colvarTextColor.MaxLength = 20;
				colvarTextColor.AutoIncrement = false;
				colvarTextColor.IsNullable = true;
				colvarTextColor.IsPrimaryKey = false;
				colvarTextColor.IsForeignKey = false;
				colvarTextColor.IsReadOnly = false;
				colvarTextColor.DefaultSetting = @"";
				colvarTextColor.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTextColor);
				
				TableSchema.TableColumn colvarImage = new TableSchema.TableColumn(schema);
				colvarImage.ColumnName = "image";
				colvarImage.DataType = DbType.String;
				colvarImage.MaxLength = 500;
				colvarImage.AutoIncrement = false;
				colvarImage.IsNullable = true;
				colvarImage.IsPrimaryKey = false;
				colvarImage.IsForeignKey = false;
				colvarImage.IsReadOnly = false;
				colvarImage.DefaultSetting = @"";
				colvarImage.ForeignKeyTableName = "";
				schema.Columns.Add(colvarImage);
				
				TableSchema.TableColumn colvarActive = new TableSchema.TableColumn(schema);
				colvarActive.ColumnName = "active";
				colvarActive.DataType = DbType.Byte;
				colvarActive.MaxLength = 0;
				colvarActive.AutoIncrement = false;
				colvarActive.IsNullable = true;
				colvarActive.IsPrimaryKey = false;
				colvarActive.IsForeignKey = false;
				colvarActive.IsReadOnly = false;
				colvarActive.DefaultSetting = @"";
				colvarActive.ForeignKeyTableName = "";
				schema.Columns.Add(colvarActive);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DbWebSiteConnectionString"].AddSchema("TblSmallBanner",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
        [DataMember]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("Subject")]
		[Bindable(true)]
        [DataMember]
		public string Subject 
		{
			get { return GetColumnValue<string>(Columns.Subject); }
			set { SetColumnValue(Columns.Subject, value); }
		}
		  
		[XmlAttribute("Subtitle")]
		[Bindable(true)]
        [DataMember]
		public string Subtitle 
		{
			get { return GetColumnValue<string>(Columns.Subtitle); }
			set { SetColumnValue(Columns.Subtitle, value); }
		}
		  
		[XmlAttribute("Link")]
		[Bindable(true)]
        [DataMember]
		public string Link 
		{
			get { return GetColumnValue<string>(Columns.Link); }
			set { SetColumnValue(Columns.Link, value); }
		}
		  
		[XmlAttribute("TextColor")]
		[Bindable(true)]
        [DataMember]
		public string TextColor 
		{
			get { return GetColumnValue<string>(Columns.TextColor); }
			set { SetColumnValue(Columns.TextColor, value); }
		}
		  
		[XmlAttribute("Image")]
		[Bindable(true)]
        [DataMember]
		public string Image 
		{
			get { return GetColumnValue<string>(Columns.Image); }
			set { SetColumnValue(Columns.Image, value); }
		}
		  
		[XmlAttribute("Active")]
		[Bindable(true)]
        [DataMember]
		public byte? Active 
		{
			get { return GetColumnValue<byte?>(Columns.Active); }
			set { SetColumnValue(Columns.Active, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varSubject,string varSubtitle,string varLink,string varTextColor,string varImage,byte? varActive)
		{
			TblSmallBanner item = new TblSmallBanner();
			
			item.Subject = varSubject;
			
			item.Subtitle = varSubtitle;
			
			item.Link = varLink;
			
			item.TextColor = varTextColor;
			
			item.Image = varImage;
			
			item.Active = varActive;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varSubject,string varSubtitle,string varLink,string varTextColor,string varImage,byte? varActive)
		{
			TblSmallBanner item = new TblSmallBanner();
			
				item.Id = varId;
			
				item.Subject = varSubject;
			
				item.Subtitle = varSubtitle;
			
				item.Link = varLink;
			
				item.TextColor = varTextColor;
			
				item.Image = varImage;
			
				item.Active = varActive;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn SubjectColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn SubtitleColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn LinkColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn TextColorColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn ImageColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn ActiveColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string Subject = @"subject";
			 public static string Subtitle = @"subtitle";
			 public static string Link = @"link";
			 public static string TextColor = @"textColor";
			 public static string Image = @"image";
			 public static string Active = @"active";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
