using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DalWebSite
{
    /// <summary>
    /// Controller class for TblTemp
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblTempController
    {
        // Preload our schema..
        TblTemp thisSchemaLoad = new TblTemp();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblTempCollection FetchAll()
        {
            TblTempCollection coll = new TblTempCollection();
            Query qry = new Query(TblTemp.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblTempCollection FetchByID(object Id)
        {
            TblTempCollection coll = new TblTempCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblTempCollection FetchByQuery(Query qry)
        {
            TblTempCollection coll = new TblTempCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblTemp.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblTemp.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Location,string Name,double? Latitude,double? Longitude)
	    {
		    TblTemp item = new TblTemp();
		    
            item.Location = Location;
            
            item.Name = Name;
            
            item.Latitude = Latitude;
            
            item.Longitude = Longitude;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string Location,string Name,double? Latitude,double? Longitude)
	    {
		    TblTemp item = new TblTemp();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Location = Location;
				
			item.Name = Name;
				
			item.Latitude = Latitude;
				
			item.Longitude = Longitude;
				
	        item.Save(UserName);
	    }
    }
}
