using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using System.Runtime.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DalWebSite
{
    /// <summary>
    /// Controller class for Temp_doctor
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TempDoctorController
    {
        // Preload our schema..
        TempDoctor thisSchemaLoad = new TempDoctor();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TempDoctorCollection FetchAll()
        {
            TempDoctorCollection coll = new TempDoctorCollection();
            Query qry = new Query(TempDoctor.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TempDoctorCollection FetchByID(object Id)
        {
            TempDoctorCollection coll = new TempDoctorCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TempDoctorCollection FetchByQuery(Query qry)
        {
            TempDoctorCollection coll = new TempDoctorCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TempDoctor.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TempDoctor.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Name,string Description,int? OldId,string Phone,string Image,DateTime? SaveDate)
	    {
		    TempDoctor item = new TempDoctor();
		    
            item.Name = Name;
            
            item.Description = Description;
            
            item.OldId = OldId;
            
            item.Phone = Phone;
            
            item.Image = Image;
            
            item.SaveDate = SaveDate;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string Name,string Description,int? OldId,string Phone,string Image,DateTime? SaveDate)
	    {
		    TempDoctor item = new TempDoctor();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Name = Name;
				
			item.Description = Description;
				
			item.OldId = OldId;
				
			item.Phone = Phone;
				
			item.Image = Image;
				
			item.SaveDate = SaveDate;
				
	        item.Save(UserName);
	    }
    }
}
